### ISSUE TITLE
I got error message: System.BadImageFormatException: Could not load file or assembly

### ISSUE THREAD

**Issue by leeklab** [nertilpoci/PeopleCounter#1]
I use VS 2017, but I got error message. Can you give me some [suggestion?

**Comment by nertilpoci** [comment]
@gbanana  i will try to reproduce this, is been a while since i opened this project

**Comment by nertilpoci** [comment]
@gbanana  finally got around to it uploaded the libraries and included both 64 and 32 bit so it should work fine on both now, if you still need it :)

**Comment by SilverioMiranda** [comment]
Where you downloaded that version of Emgu CV ? 290 ? 
I cant find any compatible version in https://sourceforge.net/projects/emgucv/files/emgucv/

Only exists 2.4.9 and 3.0, there is no such 2.9.0

**Comment by josereu** [comment]
it doesn´t works, ddls error still
